In [1]:
import tensorflow as tf

C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("hello")

In [4]:
world = tf.constant("world")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'helloworld'


In [10]:
a = tf.constant(10)

In [12]:
b = tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [20]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [22]:
result

30

In [23]:
const = tf.constant(10)

In [24]:
fill_mat = tf.fill((4,4),10)

In [25]:
myzeroes = tf.zeros((4,4))

In [26]:
myones = tf.ones((4,4))

In [27]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [28]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [29]:
myzeroes

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [30]:
myones

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [31]:
my_opes = [const,fill_mat,myzeroes,myones,myrandn,myrandu]

In [32]:
sess = tf.InteractiveSession()

In [33]:
for op in my_opes:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.38336584  2.1865652   1.0474958  -1.0690087 ]
 [ 2.3390255  -0.41952744 -0.16772999 -0.11825095]
 [ 0.16179635  0.4099318  -1.2141227   0.8554885 ]
 [-0.08424434  0.10742259 -0.6155932  -0.47240332]]


[[0.5584729  0.34245443 0.5661994  0.31708956]
 [0.52822614 0.45619476 0.60544515 0.43053448]
 [0.09375918 0.94092464 0.9906322  0.47294497]
 [0.36056423 0.3768537  0.12253916 0.6927538 ]]


