In [1]:
import numpy as np
import tensorflow as tf

C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type

In [2]:
np.random.seed(101)
tf.set_random_seed(101)

In [3]:
rand_a = np.random.uniform(0,100,(5,5))

In [4]:
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [6]:
rand_b = np.random.uniform(0,100,(5,1))

In [7]:
rand_b

array([[34.36315779],
       [86.50998163],
       [83.02777122],
       [53.81614492],
       [92.24693726]])

In [8]:
a = tf.placeholder(tf.float32)

In [10]:
b = tf.placeholder(tf.float32)

In [11]:
add_op = a+b

In [12]:
mul_op = a*b

In [17]:
with tf.Session() as sess:
    add_result=sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    print('\n')
    
    mult_result = sess.run(mul_op,feed_dict={a:rand_a,b:rand_b})
    print(mult_result)

[[ 86.00302   91.42992   37.210583  51.515327 102.890854]
 [169.89966  117.206604 175.87128  158.66437  105.503876]
 [138.45053  118.24097  101.21701  161.58795  179.5761  ]
 [ 77.05151   62.172287 114.17099  126.71542   81.440025]
 [160.77757  144.03369   97.0954   106.03387  110.94368 ]]


[[1774.5088   1960.994      97.846436  589.40265  2354.8281  ]
 [7214.04     2655.5642   7730.6445   6242.0747   1643.1614  ]
 [4601.6284   2923.673    1510.212    6522.6763   8016.1924  ]
 [1250.4379    449.69537  3248.065    3923.158    1486.6108  ]
 [6321.741    4777.169     447.255    1271.8015   1724.7173  ]]


In [18]:
n_feature = 10
n_dense_neurons = 3

In [19]:
x = tf.placeholder(tf.float32,(None,n_feature))

In [ ]:
W = tf.Variable(tf.random_normal([n_feature,n_dense_neurons]))

b = tf.Variable(tf.ones([n_dense_neurons]))